services:

    #
    # Plugin
    #
    elcodi_plugin.paypal_web_checkout:
        parent: elcodi.abstract_plugin
        arguments:
            - "Elcodi\\Plugin\\PaypalWebCheckoutBundle\\ElcodiPaypalWebCheckoutBundle"

    #
    # Plugin fields
    #
    elcodi_plugin.paypal_web_checkout.business:
        class: StdClass
        factory:
            - @elcodi_plugin.paypal_web_checkout
            - getFieldValue
        arguments:
            - business

    #
    # Paypal services
    #
    paypal_web_checkout.wrapper:
        class: %paypal_web_checkout.wrapper.class%
        arguments:
            form.factory: @form.factory
            payment.bridge: @payment.bridge
            router: @router
            business: @elcodi_plugin.paypal_web_checkout.business
            url_factory: @paypal_web_checkout.url_factory

    paypal_web_checkout.url_factory:
        class: %paypal_web_checkout.url_factory.class%
        arguments:
            router: @router
            business: @elcodi_plugin.paypal_web_checkout.business
            paypal_url: %paypal_web_checkout.api_endpoint%
            paypal_sandbox_url: %paypal_web_checkout.sandbox_api_endpoint%
            paypal_notify_validate_query_param: { cmd: _notify-validate }
            return_route_name: %paypal_web_checkout.success.route.name%
            cancel_return_route_name: %paypal_web_checkout.cancel.route.name%
            process_route_name: %paypal_web_checkout.process.route.name%
            debug: %paypal_web_checkout.debug%
