services:

    #
    # Plugin
    #
    elcodi_plugin.paypal_web_checkout:
        parent: elcodi.abstract_plugin
        arguments:
            - "Elcodi\\Plugin\\PaypalWebCheckoutBundle\\ElcodiPaypalWebCheckoutBundle"

    #
    # Plugin fields
    #
    elcodi_plugin.paypal_web_checkout.business:
        class: StdClass
        factory:
            - "@elcodi_plugin.paypal_web_checkout"
            - getFieldValue
        arguments:
            - business

    #
    # Paypal services
    #
    paypal_web_checkout.wrapper:
        class: %paypal_web_checkout.wrapper.class%
        arguments:
            - "@form.factory"
            - "@payment.bridge"
            - "@router"
            - "@elcodi_plugin.paypal_web_checkout.business"
            - "@paypal_web_checkout.url_factory"

    paypal_web_checkout.url_factory:
        class: %paypal_web_checkout.url_factory.class%
        arguments:
            - "@router"
            - "@elcodi_plugin.paypal_web_checkout.business"
            - %paypal_web_checkout.api_endpoint%
            - %paypal_web_checkout.sandbox_api_endpoint%
            - { cmd: _notify-validate }
            - %paypal_web_checkout.success.route.name%
            - %paypal_web_checkout.cancel.route.name%
            - %paypal_web_checkout.process.route.name%
            - %paypal_web_checkout.debug%
